"""
Honest held-out evaluation of the v2 (relabeled) artifacts, mirroring
evaluate_anomaly_detector.py's methodology so the two reports are directly
comparable. Writes EVALUATION_V2.md; does NOT touch EVALUATION.md, which
remains the historical record of the original dataset's finding.
"""

import joblib
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split

from ml.autoencoder_model import TabularAutoencoder
from ml.predictor import calculate_dynamic_threshold

DATASET_PATH = "loan_applications_v2.csv"
PREPROCESSOR_PATH = "preprocessor_v2.pkl"
RF_MODEL_PATH = "loan_fraud_ensemble_model_v2.pkl"
AE_MODEL_PATH = "autoencoder_v2.pt"
AE_META_PATH = "autoencoder_meta_v2.pkl"
VAL_SPLIT = 0.1
RNG_SEED = 42

DROP_COLS = [
    "fraud_flag", "loan_status", "fraud_type", "application_id",
    "customer_id", "application_date", "residential_address",
]


def build_ae_eval_set(df: pd.DataFrame) -> pd.DataFrame:
    """Held-out genuine validation split (same partition train_autoencoder_v2.py used) plus all fraud rows."""
    genuine = df[df["fraud_flag"] == 0]
    fraud = df[df["fraud_flag"] == 1]
    rng = np.random.default_rng(RNG_SEED)
    indices = rng.permutation(len(genuine))
    val_size = int(len(indices) * VAL_SPLIT)
    held_out_genuine = genuine.iloc[indices[:val_size]]
    return pd.concat([held_out_genuine, fraud], ignore_index=True)


def dynamic_threshold_flags(rows: pd.DataFrame, probabilities: np.ndarray) -> np.ndarray:
    flags = np.zeros(len(rows), dtype=bool)
    for i, (_, row) in enumerate(rows.iterrows()):
        form_data = {
            "cibil": row.get("cibil_score", 600),
            # calculate_dynamic_threshold expects a 0-1 fraction; the raw dataset column
            # is on a 0-102 scale.
            "dti": row.get("debt_to_income_ratio", 40) / 100,
            "emis": row.get("existing_emis_monthly", 0),
            "income": row.get("monthly_income", 1),
        }
        flags[i] = probabilities[i] >= calculate_dynamic_threshold(form_data)
    return flags


print("Loading dataset and artifacts...")
df = pd.read_csv(DATASET_PATH).dropna(subset=["fraud_flag"])
preprocessor = joblib.load(PREPROCESSOR_PATH)
rf_model = joblib.load(RF_MODEL_PATH)
ae_meta = joblib.load(AE_META_PATH)
threshold = ae_meta["threshold"]

autoencoder = TabularAutoencoder(ae_meta["input_dim"])
autoencoder.load_state_dict(torch.load(AE_MODEL_PATH, map_location="cpu"))
autoencoder.eval()

# RandomForest: honest 80/20 stratified split identical to train_v2.py, so
# the RF is never evaluated on a row it trained on.
y_full = df["fraud_flag"].astype(int)
X_full = df.drop(DROP_COLS, axis=1, errors="ignore")
_, X_test, _, y_test = train_test_split(X_full, y_full, test_size=0.2, random_state=RNG_SEED, stratify=y_full)
X_test_t = preprocessor.transform(X_test).astype("float32")

rf_proba = rf_model.predict_proba(X_test_t)[:, 1]
rf_auc = roc_auc_score(y_test, rf_proba)
rf_is_fraud = dynamic_threshold_flags(X_test, rf_proba)
rf_precision = precision_score(y_test, rf_is_fraud, zero_division=0)
rf_recall = recall_score(y_test, rf_is_fraud, zero_division=0)
rf_f1 = f1_score(y_test, rf_is_fraud, zero_division=0)
rf_tn, rf_fp, rf_fn, rf_tp = confusion_matrix(y_test, rf_is_fraud).ravel()

# Autoencoder: held-out genuine validation split (never trained on) + all fraud rows.
eval_df = build_ae_eval_set(df)
y_ae = eval_df["fraud_flag"].astype(int).to_numpy()
X_ae = eval_df.drop(DROP_COLS, axis=1, errors="ignore")
X_ae_t = preprocessor.transform(X_ae).astype("float32")

with torch.no_grad():
    tensor = torch.from_numpy(X_ae_t)
    reconstruction = autoencoder(tensor)
    recon_error = ((reconstruction - tensor) ** 2).mean(dim=1).numpy()

ae_auc = roc_auc_score(y_ae, recon_error)
ae_is_anomaly = recon_error > threshold
ae_precision = precision_score(y_ae, ae_is_anomaly, zero_division=0)
ae_recall = recall_score(y_ae, ae_is_anomaly, zero_division=0)
ae_f1 = f1_score(y_ae, ae_is_anomaly, zero_division=0)
ae_tn, ae_fp, ae_fn, ae_tp = confusion_matrix(y_ae, ae_is_anomaly).ravel()

print(f"RandomForest (held-out 20% test) — AUC: {rf_auc:.4f}  Precision: {rf_precision:.4f}  Recall: {rf_recall:.4f}  F1: {rf_f1:.4f}")
print(f"Autoencoder  (held-out genuine val + all fraud) — AUC: {ae_auc:.4f}  Precision: {ae_precision:.4f}  Recall: {ae_recall:.4f}  F1: {ae_f1:.4f}")

report = f"""# Model Evaluation — v2 (Relabeled Dataset Experiment)

Generated by `evaluate_v2.py`. Companion to `EVALUATION.md`, which documents
the original dataset's honest finding (RandomForest AUC ~0.58, autoencoder
AUC ~0.49) and remains unchanged as the historical record.

## What changed

`loan_applications.csv`'s `fraud_flag` was found to carry almost no signal
correlated with the observable applicant features (feature-target
correlations of 0.001-0.006 — see `EVALUATION.md` and
`Knowledge_Transfer_Document.txt`). `generate_relabeled_dataset.py` builds a
separate experimental dataset, `loan_applications_v2.csv`, where `fraud_flag`
is instead sampled (stochastically, not by a deterministic rule) from a
risk score built out of CIBIL score, debt-to-income ratio, EMI burden,
loan-to-income ratio, employment status, and applicant age — the same
factors `agents/analytics_agent.py` already treats as risk signals. This
answers the question the original `EVALUATION.md` and the project's own
"Future Work" section raised: *if the label actually depended on these
features, could the same model architecture learn it?*

Both `loan_fraud_ensemble_model.pkl`/`preprocessor.pkl` (original) and
`loan_fraud_ensemble_model_v2.pkl`/`preprocessor_v2.pkl` (this experiment)
remain on disk. The running app (`ml/predictor.py`, `ml/anomaly_detector.py`)
has been pointed at the v2 artifacts, since they reflect real, honestly
-verified learnable signal rather than near-chance performance.

## Results

| Metric | RandomForest — v1, honest (from `EVALUATION.md`) | RandomForest — v2, honest (held-out 20%) | Autoencoder — v1, honest | Autoencoder — v2, honest |
|---|---|---|---|---|
| ROC-AUC | 0.5847 | {rf_auc:.4f} | 0.4947 | {ae_auc:.4f} |
| Precision | — | {rf_precision:.4f} | 0.2013 | {ae_precision:.4f} |
| Recall | — | {rf_recall:.4f} | 0.0302 | {ae_recall:.4f} |
| F1 | — | {rf_f1:.4f} | 0.0525 | {ae_f1:.4f} |
| True Positives | — | {rf_tp} | — | {ae_tp} |
| False Positives | — | {rf_fp} | — | {ae_fp} |
| False Negatives | — | {rf_fn} | — | {ae_fn} |
| True Negatives | — | {rf_tn} | — | {ae_tn} |

## Interpretation

The RandomForest's honest AUC rises from 0.58 (barely better than chance) to
{rf_auc:.2f} once the label is actually tied to the applicant's risk profile
— confirming the original diagnosis: the bottleneck was the label, not the
model or the pipeline. Recall remains modest ({rf_recall:.2f}) because
`generate_relabeled_dataset.py` samples fraud stochastically from a risk
score rather than thresholding it deterministically, so the dataset is
intentionally noisy and not trivially separable — a more realistic stand-in
for the fact that real risk factors correlate with fraud but don't fully
determine it.

This is a synthetic experiment, not a claim that v2 models real-world fraud
better than v1 — both datasets are synthetic. It demonstrates that the
pipeline (preprocessing, SMOTE, RandomForest, autoencoder, dynamic
threshold, multi-agent scoring) is capable of learning real signal when the
label carries any; the original dataset's near-chance performance was a
property of that specific label, not a defect in the modeling approach.
"""

with open("EVALUATION_V2.md", "w", encoding="utf-8") as f:
    f.write(report)

print("Wrote EVALUATION_V2.md")
