"""
Advisory Agent — produces banking actions and compliance guidance from agent outputs.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from agents.analytics_agent import AnalyticsReport
from agents.detection_agent import DetectionReport


@dataclass
class AdvisoryItem:
    priority: str
    action: str
    rationale: str


@dataclass
class AdvisoryReport:
    agent_name: str
    role: str
    status: str
    decision: str
    items: list[AdvisoryItem] = field(default_factory=list)
    compliance_note: str = ""


class AdvisoryAgent:
    AGENT_NAME = "Advisory Agent"
    ROLE = "Fraud Operations & Lending Guidance"

    def advise(
        self,
        form_data: dict[str, Any],
        detection: DetectionReport,
        analytics: AnalyticsReport,
    ) -> AdvisoryReport:
        prediction = detection.prediction
        items: list[AdvisoryItem] = []

        if prediction.is_fraud:
            decision = "BLOCK & ESCALATE"
            status = "alert"
            items.extend(
                [
                    AdvisoryItem(
                        "P0",
                        "Freeze application workflow",
                        "Model fraud probability meets escalation threshold.",
                    ),
                    AdvisoryItem(
                        "P0",
                        "Trigger enhanced due diligence (EDD)",
                        "High composite risk; verify identity, income, and collateral documents.",
                    ),
                    AdvisoryItem(
                        "P1",
                        "Route to fraud investigation unit",
                        "Cross-check with negative files, device fingerprint, and bureau alerts.",
                    ),
                    AdvisoryItem(
                        "P1",
                        "File STR/SAR per internal policy if confirmed",
                        "Regulatory reporting may be required after investigator review.",
                    ),
                ]
            )
        elif analytics.risk_score >= 45 or prediction.probability >= 0.3:
            decision = "MANUAL REVIEW"
            status = "warning"
            items.extend(
                [
                    AdvisoryItem(
                        "P1",
                        "Assign senior credit analyst",
                        "Borderline model score with elevated feature risk.",
                    ),
                    AdvisoryItem(
                        "P2",
                        "Request updated income proof and bank statements",
                        "Validate DTI and EMI assumptions from application.",
                    ),
                    AdvisoryItem(
                        "P2",
                        "Apply 90-day enhanced monitoring post-disbursement",
                        "Early-warning triggers on repayment behavior.",
                    ),
                ]
            )
        else:
            decision = "STANDARD APPROVAL PATH"
            status = "success"
            items.extend(
                [
                    AdvisoryItem(
                        "P2",
                        "Proceed with standard KYC and credit underwriting",
                        "Low model and feature risk profile.",
                    ),
                    AdvisoryItem(
                        "P3",
                        "Schedule routine portfolio monitoring",
                        "Baseline surveillance per lending policy.",
                    ),
                ]
            )

        high_signals = [s for s in analytics.signals if s.severity == "high"]
        for signal in high_signals[:2]:
            items.append(
                AdvisoryItem(
                    "P2",
                    f"Mitigate: {signal.factor}",
                    signal.detail,
                )
            )

        compliance = (
            "Advisory generated by RiskSense AI agent pipeline. "
            "Final disposition remains with authorized bank officers; "
            "this is decision support, not autonomous approval."
        )

        return AdvisoryReport(
            agent_name=self.AGENT_NAME,
            role=self.ROLE,
            status=status,
            decision=decision,
            items=items,
            compliance_note=compliance,
        )
